# -*- coding: utf-8 -*-
"""Colour_Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q7zbe0mkJ3XGjKldmKX96ClRKv6q28Om
"""

import cv2
import pandas as pd

img_path = 'building.jpg'
csv_path = 'colors.csv'

img = cv2.imread(img_path)
img = cv2.resize(img, (800,600))

clicked = False
r = g = b = xpos = ypos = 0

def get_color_name(R,G,B):
	minimum = 1000
	for i in range(len(df)):
		d = abs(R - int(df.loc[i,'R'])) + abs(G - int(df.loc[i,'G'])) + abs(B - int(df.loc[i,'B']))
		if d <= minimum:
			minimum = d
			cname = df.loc[i, 'color_name']

	return cname

def draw_function(event, x, y, flags, params):
	if event == cv2.EVENT_LBUTTONDBLCLK:
		global b, g, r, xpos, ypos, clicked
		clicked = True
		xpos = x
		ypos = y
		b,g,r = image[y,x]
		b = int(b)
		g = int(g)
		r = int(r)

import cv2
cv2.namedWindow('image')
cv2.setMouseCallback('image', draw_function)

from google.colab.patches import cv2_imshow
img_path = 'building.jpg'
csv_path = 'colors.csv'
import cv2
img = cv2.imread(img_path)
img = cv2.resize(img, (800,600))
while(1):
  cv2_imshow(img)
if (clicked):
        cv2.rectangle(img,(20,20), (750,60), (b,g,r), -1)
        text = getColorName(r,g,b)+'R='+str(r)+'G='+ str(g)+'B='+ str(b)
        cv2.putText(img, text,(50,50),2,0.8,(255,255,255),2,cv2.LINE_AA)
        if(r+g+b>=600):
            cv2.putText(img, text,(50,50),2,0.8,(0,0,0),2,cv2.LINE_AA)
            
        clicked=False
if cv2.waitKey(20) & 0xFF ==27:
        break
cv2.destroyAllWindows()